### ISSUE TITLE
Track numbers are sorted and played "alphabetically"

### ISSUE THREAD

**Issue by ghost** [digimezzo/dopamine-windows#869]
## I'm submitting a...

<pre><code>
[ ] Regression 
[X] Bug report  
[ ] Feature request
</code></pre>

## I'm using these versions

* Windows version: Windows 10
* Dopamine version: 2.0 (Preview 1)

## Reproduction steps

When going from Windows/local folder:

* Step 1: Open local music folder (On Windows, not on Dopamine)
* Step 2: Select album that you want to play
* Step 3: Select the "Play" button at the top of the folder (on Windows still, not on Dopamine)
* Step 4: The album now starts playing in Dopamine (Dopamine is set as default player)
* Step 5: The tracks are displayed AND play in the wrong order

## Observed behavior

The tracks are sorted "alphabetically" and will play in this order: 1, 10, 11, 12, 13, ..., 2, 21, 22, 23...

## Desired behavior

Dopamine should sort and play the tracks in this order: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...

## Log file

[Dopamine.log](https://github.com/digimezzo/Dopamine/files/2454234/Dopamine.log)

**Comment by ghost** [comment]
Hi,

Any update on this issue?

Thank you.

**Comment by digimezzo** [comment]
@HZK-hime Could you try Preview 2 or 3? This issue was fixed since Preview 2.

**Comment by ghost** [comment]
@digimezzo The issue still persists will Preview 2, Preview 3 and Preview 4 when playing from a Windows folder. Plus, on all three versions, when starting an album, the player does not switch to said album on the right pane like version 1.5.14 (Release) used to.

**Comment by digimezzo** [comment]
@HZK-hime  Could you attach a screenshot of what you are seeing for the album issue instead of the actual album? 

As for the track order issue, I couldn't reproduce it with previews 2 and 3, while I could reproduce it with preview 1. Could you attach a screenshot of the file names and the order that they appear in the Windows folder?

**Comment by ghost** [comment]
@digimezzo Here are the screenshots for the track order issue, this is from Preview 3:

With Dopamine closed, I went to my music folder, and did "Play All" from the album I wanted. This launched Dopamine. We can see that the album starts playing with Track 1:

![track1](https://user-images.githubusercontent.com/43936988/48871134-71db6c80-edb1-11e8-9624-d5a5437b3ee0.png)

Then, after the first track was done playing, the player went to track 10 instead of going to track 2:

![track10](https://user-images.githubusercontent.com/43936988/48871156-83bd0f80-edb1-11e8-9643-a5829021334e.png)

The player will then play track 11, 12, 13 and 14 (the end of this album) and then go to track 2 and proceed from there.

This is how my files appear in the Windows folder:

![windows_album](https://user-images.githubusercontent.com/43936988/48871203-b109bd80-edb1-11e8-8c22-4b270d6553b0.png)

This issue has been happening with every version released so far.

Thank you.

**Comment by digimezzo** [comment]
@HZK-hime Ok, I now see what you mean. Sorry this took so long. I can reproduce the issue and will fix it immediately.

**Comment by arc-tec** [comment]
this bug seems to persist into preview 13, and into folder view

![image](https://user-images.githubusercontent.com/35627686/63387515-7cd02700-c35a-11e9-9660-19f705ea8cb0.png)
